name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    # Set the correct working directory if package.json is in ClientApp folder
    - name: Install dependencies
      run: npm install
      working-directory: ./BadHabitApp/ClientApp  # Adjust this to the actual path

    - name: Build frontend
      run: npm run build
      working-directory: ./BadHabitApp/ClientApp

    - name: Run Angular unit tests
      run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      working-directory: ./BadHabitApp/ClientApp

    - name: Archive frontend test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: frontend-test-results
        path: ClientApp/coverage/  # Adjust the path to the coverage folder

  build-backend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'  # Ensure this matches your .NET version

    - name: Install dependencies
      run: dotnet restore ./BadHabitApp

    - name: Build backend
      run: dotnet build ./BadHabitApp --configuration Release

    - name: Run backend tests
      run: dotnet test ./BadHabitApp/BadHabitApp.Tests --logger "trx;LogFileName=test_results.trx"

    - name: Archive backend test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: backend-test-results
        path: ./BadHabitApp/BadHabitApp.Tests/TestResults  # Adjust path if necessary